"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable */
/**
 * @const
 * @namespace
 */
var NationalInstruments = NationalInstruments || {};
/**
 * @const
 * @namespace
 */
NationalInstruments.PackedData = NationalInstruments.PackedData || {};
/**
 * @enum
 */
NationalInstruments.PackedData.AnyValue = {
    NONE: 0,
    PackedBooleanValue: 1,
    PackedInt8Value: 2,
    PackedUInt8Value: 3,
    PackedInt16Value: 4,
    PackedUInt16Value: 5,
    PackedInt32Value: 6,
    PackedUInt32Value: 7,
    PackedInt64Value: 8,
    PackedUInt64Value: 9,
    PackedFloat32Value: 10,
    PackedFloat64Value: 11,
    PackedStringValue: 12,
    PackedBlittableArrayValue: 13,
    PackedArrayValue: 14,
    PackedClusterValue: 15,
    PackedWaveformValue: 16
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedBooleanValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedBooleanValue}
 */
NationalInstruments.PackedData.PackedBooleanValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedBooleanValue=} obj
 * @returns {NationalInstruments.PackedData.PackedBooleanValue}
 */
NationalInstruments.PackedData.PackedBooleanValue.getRootAsPackedBooleanValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedBooleanValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {boolean}
 */
NationalInstruments.PackedData.PackedBooleanValue.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedBooleanValue.startPackedBooleanValue = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} value
 */
NationalInstruments.PackedData.PackedBooleanValue.addValue = function (builder, value) {
    builder.addFieldInt8(0, +value, +false);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBooleanValue.endPackedBooleanValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedInt8Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedInt8Value}
 */
NationalInstruments.PackedData.PackedInt8Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedInt8Value=} obj
 * @returns {NationalInstruments.PackedData.PackedInt8Value}
 */
NationalInstruments.PackedData.PackedInt8Value.getRootAsPackedInt8Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedInt8Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedInt8Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedInt8Value.startPackedInt8Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedInt8Value.addValue = function (builder, value) {
    builder.addFieldInt8(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt8Value.endPackedInt8Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedUInt8Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedUInt8Value}
 */
NationalInstruments.PackedData.PackedUInt8Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedUInt8Value=} obj
 * @returns {NationalInstruments.PackedData.PackedUInt8Value}
 */
NationalInstruments.PackedData.PackedUInt8Value.getRootAsPackedUInt8Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedUInt8Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedUInt8Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedUInt8Value.startPackedUInt8Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedUInt8Value.addValue = function (builder, value) {
    builder.addFieldInt8(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt8Value.endPackedUInt8Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedInt16Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedInt16Value}
 */
NationalInstruments.PackedData.PackedInt16Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedInt16Value=} obj
 * @returns {NationalInstruments.PackedData.PackedInt16Value}
 */
NationalInstruments.PackedData.PackedInt16Value.getRootAsPackedInt16Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedInt16Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedInt16Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedInt16Value.startPackedInt16Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedInt16Value.addValue = function (builder, value) {
    builder.addFieldInt16(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt16Value.endPackedInt16Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedUInt16Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedUInt16Value}
 */
NationalInstruments.PackedData.PackedUInt16Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedUInt16Value=} obj
 * @returns {NationalInstruments.PackedData.PackedUInt16Value}
 */
NationalInstruments.PackedData.PackedUInt16Value.getRootAsPackedUInt16Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedUInt16Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedUInt16Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedUInt16Value.startPackedUInt16Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedUInt16Value.addValue = function (builder, value) {
    builder.addFieldInt16(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt16Value.endPackedUInt16Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedInt32Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedInt32Value}
 */
NationalInstruments.PackedData.PackedInt32Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedInt32Value=} obj
 * @returns {NationalInstruments.PackedData.PackedInt32Value}
 */
NationalInstruments.PackedData.PackedInt32Value.getRootAsPackedInt32Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedInt32Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedInt32Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedInt32Value.startPackedInt32Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedInt32Value.addValue = function (builder, value) {
    builder.addFieldInt32(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt32Value.endPackedInt32Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedUInt32Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedUInt32Value}
 */
NationalInstruments.PackedData.PackedUInt32Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedUInt32Value=} obj
 * @returns {NationalInstruments.PackedData.PackedUInt32Value}
 */
NationalInstruments.PackedData.PackedUInt32Value.getRootAsPackedUInt32Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedUInt32Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedUInt32Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedUInt32Value.startPackedUInt32Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedUInt32Value.addValue = function (builder, value) {
    builder.addFieldInt32(0, value, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt32Value.endPackedUInt32Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedInt64Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedInt64Value}
 */
NationalInstruments.PackedData.PackedInt64Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedInt64Value=} obj
 * @returns {NationalInstruments.PackedData.PackedInt64Value}
 */
NationalInstruments.PackedData.PackedInt64Value.getRootAsPackedInt64Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedInt64Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {flatbuffers.Long}
 */
NationalInstruments.PackedData.PackedInt64Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedInt64Value.startPackedInt64Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} value
 */
NationalInstruments.PackedData.PackedInt64Value.addValue = function (builder, value) {
    builder.addFieldInt64(0, value, builder.createLong(0, 0));
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedInt64Value.endPackedInt64Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedUInt64Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedUInt64Value}
 */
NationalInstruments.PackedData.PackedUInt64Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedUInt64Value=} obj
 * @returns {NationalInstruments.PackedData.PackedUInt64Value}
 */
NationalInstruments.PackedData.PackedUInt64Value.getRootAsPackedUInt64Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedUInt64Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {flatbuffers.Long}
 */
NationalInstruments.PackedData.PackedUInt64Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedUInt64Value.startPackedUInt64Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} value
 */
NationalInstruments.PackedData.PackedUInt64Value.addValue = function (builder, value) {
    builder.addFieldInt64(0, value, builder.createLong(0, 0));
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedUInt64Value.endPackedUInt64Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedFloat32Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedFloat32Value}
 */
NationalInstruments.PackedData.PackedFloat32Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedFloat32Value=} obj
 * @returns {NationalInstruments.PackedData.PackedFloat32Value}
 */
NationalInstruments.PackedData.PackedFloat32Value.getRootAsPackedFloat32Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedFloat32Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedFloat32Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedFloat32Value.startPackedFloat32Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedFloat32Value.addValue = function (builder, value) {
    builder.addFieldFloat32(0, value, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedFloat32Value.endPackedFloat32Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedFloat64Value = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedFloat64Value}
 */
NationalInstruments.PackedData.PackedFloat64Value.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedFloat64Value=} obj
 * @returns {NationalInstruments.PackedData.PackedFloat64Value}
 */
NationalInstruments.PackedData.PackedFloat64Value.getRootAsPackedFloat64Value = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedFloat64Value).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedFloat64Value.prototype.value = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedFloat64Value.startPackedFloat64Value = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
NationalInstruments.PackedData.PackedFloat64Value.addValue = function (builder, value) {
    builder.addFieldFloat64(0, value, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedFloat64Value.endPackedFloat64Value = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedStringValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedStringValue}
 */
NationalInstruments.PackedData.PackedStringValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedStringValue=} obj
 * @returns {NationalInstruments.PackedData.PackedStringValue}
 */
NationalInstruments.PackedData.PackedStringValue.getRootAsPackedStringValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedStringValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
NationalInstruments.PackedData.PackedStringValue.prototype.value = function (optionalEncoding) {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedStringValue.startPackedStringValue = function (builder) {
    builder.startObject(1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedStringValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(0, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedStringValue.endPackedStringValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedBlittableArrayValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedBlittableArrayValue}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedBlittableArrayValue=} obj
 * @returns {NationalInstruments.PackedData.PackedBlittableArrayValue}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.getRootAsPackedBlittableArrayValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedBlittableArrayValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {number} index
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.dimensions = function (index) {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.dimensionsLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @returns {Int32Array}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.dimensionsArray = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? new Int32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};
/**
 * @param {number} index
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.value = function (index) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.valueLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @returns {Int8Array}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.prototype.valueArray = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.startPackedBlittableArrayValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dimensionsOffset
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.addDimensions = function (builder, dimensionsOffset) {
    builder.addFieldOffset(0, dimensionsOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.createDimensionsVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addInt32(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.startDimensionsVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(1, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.createValueVector = function (builder, data) {
    builder.startVector(1, data.length, 1);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addInt8(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.startValueVector = function (builder, numElems) {
    builder.startVector(1, numElems, 1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittableArrayValue.endPackedBlittableArrayValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedBlittable1DArrayValue}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedBlittable1DArrayValue=} obj
 * @returns {NationalInstruments.PackedData.PackedBlittable1DArrayValue}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.getRootAsPackedBlittable1DArrayValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedBlittable1DArrayValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.length = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};
/**
 * @param {number} index
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.value = function (index) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.valueLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @returns {Int8Array}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.prototype.valueArray = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.startPackedBlittable1DArrayValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} length
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.addLength = function (builder, length) {
    builder.addFieldInt32(0, length, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(1, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.createValueVector = function (builder, data) {
    builder.startVector(1, data.length, 1);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addInt8(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.startValueVector = function (builder, numElems) {
    builder.startVector(1, numElems, 1);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedBlittable1DArrayValue.endPackedBlittable1DArrayValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedArrayValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedArrayValue}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedArrayValue=} obj
 * @returns {NationalInstruments.PackedData.PackedArrayValue}
 */
NationalInstruments.PackedData.PackedArrayValue.getRootAsPackedArrayValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedArrayValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {number} index
 * @param {NationalInstruments.PackedData.PackedDataValue=} obj
 * @returns {NationalInstruments.PackedData.PackedDataValue}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.value = function (index, obj) {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? (obj || new NationalInstruments.PackedData.PackedDataValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.valueLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @param {number} index
 * @returns {number}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.dimensions = function (index) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readInt32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.dimensionsLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @returns {Int32Array}
 */
NationalInstruments.PackedData.PackedArrayValue.prototype.dimensionsArray = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? new Int32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedArrayValue.startPackedArrayValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedArrayValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(0, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedArrayValue.createValueVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addOffset(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedArrayValue.startValueVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dimensionsOffset
 */
NationalInstruments.PackedData.PackedArrayValue.addDimensions = function (builder, dimensionsOffset) {
    builder.addFieldOffset(1, dimensionsOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedArrayValue.createDimensionsVector = function (builder, data) {
    builder.startVector(4, data.length, 4);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addInt32(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedArrayValue.startDimensionsVector = function (builder, numElems) {
    builder.startVector(4, numElems, 4);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedArrayValue.endPackedArrayValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedWaveformValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedWaveformValue}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedWaveformValue=} obj
 * @returns {NationalInstruments.PackedData.PackedWaveformValue}
 */
NationalInstruments.PackedData.PackedWaveformValue.getRootAsPackedWaveformValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedWaveformValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.t0 = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.dt = function () {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};
/**
 * @param {number} index
 * @returns {number}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.data = function (index) {
    var offset = this.bb.__offset(this.bb_pos, 8);
    return offset ? this.bb.readFloat64(this.bb.__vector(this.bb_pos + offset) + index * 8) : 0;
};
/**
 * @returns {number}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.dataLength = function () {
    var offset = this.bb.__offset(this.bb_pos, 8);
    return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};
/**
 * @returns {Float64Array}
 */
NationalInstruments.PackedData.PackedWaveformValue.prototype.dataArray = function () {
    var offset = this.bb.__offset(this.bb_pos, 8);
    return offset ? new Float64Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedWaveformValue.startPackedWaveformValue = function (builder) {
    builder.startObject(3);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} t0
 */
NationalInstruments.PackedData.PackedWaveformValue.addT0 = function (builder, t0) {
    builder.addFieldFloat64(0, t0, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} dt
 */
NationalInstruments.PackedData.PackedWaveformValue.addDt = function (builder, dt) {
    builder.addFieldFloat64(1, dt, 0.0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
NationalInstruments.PackedData.PackedWaveformValue.addData = function (builder, dataOffset) {
    builder.addFieldOffset(2, dataOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedWaveformValue.createDataVector = function (builder, data) {
    builder.startVector(8, data.length, 8);
    for (var i = data.length - 1; i >= 0; i--) {
        builder.addFloat64(data[i]);
    }
    return builder.endVector();
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
NationalInstruments.PackedData.PackedWaveformValue.startDataVector = function (builder, numElems) {
    builder.startVector(8, numElems, 8);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedWaveformValue.endPackedWaveformValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedClusterValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedClusterValue}
 */
NationalInstruments.PackedData.PackedClusterValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedClusterValue=} obj
 * @returns {NationalInstruments.PackedData.PackedClusterValue}
 */
NationalInstruments.PackedData.PackedClusterValue.getRootAsPackedClusterValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedClusterValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedClusterValue.startPackedClusterValue = function (builder) {
    builder.startObject(0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedClusterValue.endPackedClusterValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @constructor
 */
NationalInstruments.PackedData.PackedDataValue = function () {
    /**
     * @type {flatbuffers.ByteBuffer}
     */
    this.bb = null;
    /**
     * @type {number}
     */
    this.bb_pos = 0;
};
/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {NationalInstruments.PackedData.PackedDataValue}
 */
NationalInstruments.PackedData.PackedDataValue.prototype.__init = function (i, bb) {
    this.bb_pos = i;
    this.bb = bb;
    return this;
};
/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {NationalInstruments.PackedData.PackedDataValue=} obj
 * @returns {NationalInstruments.PackedData.PackedDataValue}
 */
NationalInstruments.PackedData.PackedDataValue.getRootAsPackedDataValue = function (bb, obj) {
    return (obj || new NationalInstruments.PackedData.PackedDataValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};
/**
 * @returns {NationalInstruments.PackedData.AnyValue}
 */
NationalInstruments.PackedData.PackedDataValue.prototype.valueType = function () {
    var offset = this.bb.__offset(this.bb_pos, 4);
    return offset ? /** @type {NationalInstruments.PackedData.AnyValue} */ (this.bb.readUint8(this.bb_pos + offset)) : NationalInstruments.PackedData.AnyValue.NONE;
};
/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
NationalInstruments.PackedData.PackedDataValue.prototype.value = function (obj) {
    var offset = this.bb.__offset(this.bb_pos, 6);
    return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};
/**
 * @param {flatbuffers.Builder} builder
 */
NationalInstruments.PackedData.PackedDataValue.startPackedDataValue = function (builder) {
    builder.startObject(2);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {NationalInstruments.PackedData.AnyValue} valueType
 */
NationalInstruments.PackedData.PackedDataValue.addValueType = function (builder, valueType) {
    builder.addFieldInt8(0, valueType, NationalInstruments.PackedData.AnyValue.NONE);
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
NationalInstruments.PackedData.PackedDataValue.addValue = function (builder, valueOffset) {
    builder.addFieldOffset(1, valueOffset, 0);
};
/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
NationalInstruments.PackedData.PackedDataValue.endPackedDataValue = function (builder) {
    var offset = builder.endObject();
    return offset;
};
/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
NationalInstruments.PackedData.PackedDataValue.finishPackedDataValueBuffer = function (builder, offset) {
    builder.finish(offset);
};
// Exports for Node.js and RequireJS
this.NationalInstruments = NationalInstruments;
//# sourceMappingURL=PackedDataValues_generated.js.map